#!/usr/bin/env bash

case "$1" in
    1)
    echo "aestheticLight" > ~/.config/i3/theme/now
    echo "Theme changed to : Aesthetic - Light"
    ;;
    2)
    echo "aestheticDark" > ~/.config/i3/theme/now
    echo "Theme changed to : Aesthetic - Dark"
    ;;
    *)
    echo "aestheticLight" > ~/.config/i3/theme/now
    echo "Theme changed to : Aesthetic - Light"
    ;;
esac

~/.config/i3/kill-ui &> /dev/null
~/.config/i3/startup &> /dev/null
