#!/usr/bin/env bash

case "$1" in
    1)
    sed -i '9s_THEME=.*_THEME="aetherLight"_' ~/.aether-corevar
    ;;
    2)
    sed -i '9s_THEME=.*_THEME="aetherDark"_' ~/.aether-corevar
    ;;
    *)
    sed -i '9s_THEME=.*_THEME="aetherLight"_' ~/.aether-corevar
    ;;
esac

~/.config/i3/kill-ui &> /dev/null
~/.config/i3/startup &> /dev/null
