#!/usr/bin/env bash

# Load Global Variable
source $HOME/.aether-corevar

aetherLight() {
    # Dunst
    dunst -config ~/.config/dunst/dunstrc-left &
    # GTK, rofi, color theme
    ~/.config/i3/theme/aether-light/aether-light-theme
    # Panel
    tint2 -c ~/.config/tint2/aether-i3-light.tint2rc &
    # Terminal Color Scheme
    xrdb ~/.config/i3/theme/aether-light/.Xresources
    # Screenshot frame color
    sed -i '11s_SSFRAME=.*_SSFRAME="#f9f9f9"_' ~/.aether-corevar
    # Notify
    $NOTIFIER -r 13 -i "$ICONDIR/theme.png" -t 2000 -u low "Light Mode" "Change Theme"
    # Live Reload GTK Theme
    timeout 0.1s xsettingsd -c ~/.config/i3/theme/aether-light/.xsettingsd 
}
aetherDark() {
    # Dunst
    dunst -config ~/.config/dunst/dunstrc-dark-left &
    # GTK, rofi, color theme
    ~/.config/i3/theme/aether-dark/aether-dark-theme
    # Panel
    tint2 -c ~/.config/tint2/aether-i3-dark.tint2rc &
    # Terminal Color Scheme
    xrdb ~/.config/i3/theme/aether-dark/.Xresources
    # Screenshot frame color
    sed -i '11s_SSFRAME=.*_SSFRAME="#21252B"_' ~/.aether-corevar
    # Notify
    $NOTIFIER -r 13 -i "$ICONDIR/theme.png" -t 2000 -u low "Dark Mode" "Change Theme"
    # Live Reload GTK Theme
    timeout 0.1s xsettingsd -c ~/.config/i3/theme/aether-dark/.xsettingsd
}

# Load rofi theme based on resolution
~/.config/i3/scripts/change-resolution $RESOLUTION

# Load Theme
"$THEME"

# Wallpaper
~/.config/i3/scripts/wallpaper &> /dev/null

exit

